# Generated by Django 4.0.5 on 2022-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrealumno', models.CharField(max_length=35, verbose_name='Nombre del alumno')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad del Alumno')),
                ('cursosrealizados', models.PositiveSmallIntegerField(verbose_name='Cursos Realizados')),
                ('telefono', models.PositiveIntegerField(verbose_name='Numero telefonico alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprofesor', models.CharField(max_length=35, verbose_name='Nombre del profesor')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad del Profesor')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Basico'), (2, 'Intermedio'), (3, 'Avanzado')], verbose_name='Nivel')),
            ],
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='nombrecurso',
        ),
    ]
